### ISSUE TITLE
Clementine does not read usb drive

### ISSUE THREAD

**Issue by nonoayay** [kz6fittycent/clementine#4]
I have Linux os on a ssd drive and all data on usb drives. Clementine can not read those usb drives, can read only the files on the ssd drive.

Any solution?

**Comment by kz6fittycent** [comment]
Nothing as of yet. I've been working on that for some time. 

EDIT:

Looks like I've missed this simple solution: `snap connect clementine:removable-media`

**Comment by kz6fittycent** [comment]
Run this command: `snap connect clementine:removable-media`

**Comment by nonoayay** [comment]
Thank you it works perfectly. And it works for all snaps, I did the same for gimp, with same result. thank as well for clementine.

**Comment by Waddlen** [comment]
@kz6fittycent Would it be possible to enable this by default? Clementine is not able to access data on secondary disks without running `snap connect clementine:removable-media`. Fussing with the terminal is abrasive to inexperienced users. Thanks!

**Comment by kz6fittycent** [comment]
> @kz6fittycent Would it be possible to enable this by default? Clementine is not able to access data on secondary disks without running `snap connect clementine:removable-media`. Fussing with the terminal is abrasive to inexperienced users. Thanks!

No I'm afraid that's something that is controlled by snapd. That's not connected by default. The user has to "opt-in" since that is considered a security risk. Remember, snaps place security higher in the hierarchy than do native packages. If you want an easy method to control interfaces, you can install the snap-store `sudo snap install snap-store`. This allows you to use the GUI to manage your interfaces. I use it all the time :) .

**Comment by merlijn-sebrechts** [comment]
@kz6fittycent the process for requesting `removable-media` auto-connection has recently been changed and Clementine will probably be granted it if you request it. However, it has to be the publisher who requests it.

For more info, see: https://snapcraft.io/docs/removable-media-interface
